# Numpy - Sesi 4

In [1]:
import numpy as np

In [2]:
# cek version
np.__version__

'1.16.5'

In [6]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [7]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
a[2]

array([ 9, 10, 11, 12])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [13]:
# array with range of elements
print(np.arange(4))
print(np.arange(0,10,2)) #start stop step

[0 1 2 3]
[0 2 4 6 8]


In [14]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [15]:
np.arange(-2,10,2)

array([-2,  0,  2,  4,  6,  8])

## add , remove , and sort

In [16]:
arr= np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.append(arr,[9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.delete(arr, 1) #delete berdasarkan index

array([1, 3, 4, 5, 6, 7, 8])

In [19]:
arr= np.array([2,1,3,4,5,6,7,8])
arr

array([2, 1, 3, 4, 5, 6, 7, 8])

In [20]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## shape and size

In [21]:
arr.ndim

1

In [22]:
arr.size

8

In [23]:
arr.shape

(8,)

In [27]:
arr = np.array([[[0,1,2,3],
         [4,5,6,7]],
         
        [[0,1,2,3],
        [4,5,6,7]],
         
         [[0,1,2,3],
         [4,5,6,7]]]
        )

In [28]:
arr

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [29]:
arr.ndim

3

In [30]:
arr.size

24

In [31]:
arr.shape

(3, 2, 4)

In [33]:
arr= np.array([[1,2,3,4,5],])
arr

array([[1, 2, 3, 4, 5]])

In [34]:
arr.ndim

2

In [35]:
arr.size

5

In [36]:
arr.shape

(1, 5)

In [37]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [38]:
a.reshape(3,2) # 3 row dan 2 kolom

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [40]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

## convert 1D to 2D

In [41]:
a= np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [42]:
a.shape

(6,)

In [44]:
a2 = a[np.newaxis]
a2.shape

(1, 6)

In [46]:
print(a2)

[[1 2 3 4 5 6]]


In [47]:
row_vector = a[np.newaxis, :]

In [48]:
print(row_vector.shape)

(1, 6)


In [49]:
print(row_vector)

[[1 2 3 4 5 6]]


In [51]:
col_vector = a[:, np.newaxis]

In [52]:
print(col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [53]:
col_vector.shape

(6, 1)

In [54]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [56]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [57]:
print(b)
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


## indexing dan slicing

In [58]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [61]:
data[0]

1

In [62]:
data[1]

2

In [63]:
data[2]

3

In [64]:
print(data[0:2])

[1 2]


In [66]:
print(data[1:])

[2 3]


In [67]:
print(data[-2])

2


In [69]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [72]:
condition = (a>= 5)
a[condition]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
condition = (a%2 == 0)
a[condition]

array([ 2,  4,  6,  8, 10, 12])

In [75]:
condition = ((a>2) & (a<12))
a[condition]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

## Creating array from existing data

In [76]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [80]:
a_1= np.array([[1,1],[2,2]])
a_2 = np.array([[3,3], [4,4]]) 

In [81]:
a_1

array([[1, 1],
       [2, 2]])

In [82]:
a_2

array([[3, 3],
       [4, 4]])

In [85]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [86]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [87]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
    [13,14,15,16,17,18,19,20,21,22,23,24]
])

arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [88]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [90]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
a.shape

(3, 4)

In [93]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
b = a.copy()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic array operations

In [95]:
a = np.array([1,2,3,4])

#add all of the elements in the array
a.sum()

10

In [97]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [98]:
# sum all the rows
b.sum(axis=0)

array([3, 3])

In [100]:
# sum all the columns
b.sum(axis=1)

array([2, 4])

In [101]:
b.sum()

6

In [102]:
data = np.array([1,2])
data

array([1, 2])

In [103]:
ones = np.ones(2)
ones

array([1., 1.])

In [104]:
data +ones

array([2., 3.])

In [105]:
data * data

array([1, 4])

In [106]:
data / data

array([1., 1.])

In [107]:
data ** data

array([1, 4], dtype=int32)

## Broadcasting

In [108]:
data * 2

array([2, 4])

In [109]:
data * 1.6

array([1.6, 3.2])

## More array operations

In [110]:
data.min()

1

In [111]:
data.max()

2

In [112]:
data.sum()

3

In [113]:
data.std()

0.5

# Matrices

## creating matrices

In [115]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [116]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [117]:
np.random.random((3,2))

array([[0.83876942, 0.06365037],
       [0.41207871, 0.07022658],
       [0.66626029, 0.46927414]])

## Matrix Arithmetic

In [118]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [119]:
ones = np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [120]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


## Dot product

In [123]:
a_1 = np.array([[1,2,3],[4,5,6]])
a_1.shape

(2, 3)

In [124]:
a_2 = np.array([[7,8],[9,10],[11,12]])
a_2.shape

(3, 2)

In [125]:
# dot product
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix indexing

In [126]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
data[0]

array([1, 2])

In [128]:
data[0,1]

2

In [129]:
data[1]

array([3, 4])

In [130]:
data[1,1]

4

In [131]:
data[0:2, 1]

array([2, 4])

# Matrix Aggregation

In [132]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [133]:
print(data.min())
print(data.max())
print(data.sum())

1
6
21


In [134]:
print(data.max(axis=0))

[5 6]


In [135]:
print(data.max(axis=1))

[2 4 6]


## Transposing and reshaping

In [136]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [137]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [141]:
data_col = np.array([[1,2,3,4,5,6]]).T


In [142]:
data_col

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [143]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [145]:
 np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [146]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

# N-dimensional Array

In [148]:
ndarr = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [149]:
ndarr.shape

(2, 2, 2)

In [150]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [151]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [152]:
np.random.random((4,3,2))

array([[[0.17673112, 0.43030981],
        [0.06163361, 0.49630002],
        [0.25149588, 0.1301783 ]],

       [[0.97735217, 0.46506723],
        [0.13126655, 0.87289795],
        [0.83595302, 0.94915239]],

       [[0.99537704, 0.9182439 ],
        [0.19489089, 0.9237921 ],
        [0.01925478, 0.41457075]],

       [[0.97739545, 0.93872317],
        [0.25985118, 0.63343071],
        [0.83272629, 0.79767706]]])

# Flatten N-Dimensional Array

In [154]:
arrflat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arrflat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [155]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [157]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Working with Math Formulas

In [ ]:
error = (1/n) * np.sum(np.square(observed-prediction)) 