# Data Structures

## List

In [1]:
my_list = [1,2,3]

In [2]:
print(my_list)

[1, 2, 3]


In [4]:
my_list + [4,5]

[1, 2, 3, 4, 5]

In [5]:
print(my_list * 2)

[1, 2, 3, 1, 2, 3]


In [6]:
my_list.append(4)

In [7]:
print(my_list)

[1, 2, 3, 4]


In [8]:
mylist = [1, 2, 3]
print(mylist)

[1, 2, 3]


In [9]:
mylist.extend([4,5,6])

In [10]:
print(mylist)

[1, 2, 3, 4, 5, 6]


In [11]:
mylist.remove(4)

In [12]:
print(mylist)

[1, 2, 3, 5, 6]


In [13]:
my_list.append([4,5])
print(my_list)

[1, 2, 3, 4, [4, 5]]


In [14]:
my_list.remove([4,5])

In [15]:
print(my_list)

[1, 2, 3, 4]


## Dictionaries

In [1]:
student = {'name': 'Raka', 'age':18}

In [2]:
employee = {'cto': {'name': 'Raka', 'age':18}}

In [3]:
student = dict(name='Billy', age=38)

In [4]:
print(student['name'])

Billy


In [5]:
print(student['age'])

38


In [6]:
print(student)

{'name': 'Billy', 'age': 38}


In [7]:
del student['age']

In [8]:
print(student)

{'name': 'Billy'}


In [9]:
student = {'name': 'Raka', 'age':17}

In [10]:
print(student.keys())

dict_keys(['name', 'age'])


In [11]:
print(student.values())

dict_values(['Raka', 17])


## Tuples
sekumpulan objek yang diawali dan diakhir dengan ()
tuples tidak bisa diubah ubah nantinya

In [12]:
people = ('Raka', ('kode', 'random'))

In [13]:
print(people)

('Raka', ('kode', 'random'))


In [15]:
print(people[0])

Raka


In [16]:
print(people[1])

('kode', 'random')


In [17]:
print(people[1][1])

random


In [18]:
print(people[1][0])

kode


In [19]:
numbers = (1,2,3,4)

In [20]:
new_numbers = numbers[0], numbers[1:3]

In [21]:
print(new_numbers)

(1, (2, 3))


In [22]:
print(numbers)

(1, 2, 3, 4)


In [23]:
email_attr = ('to', 'from', 'cc', 'bcc', 'subject','body')

In [24]:
# agar bisa di sort convert dulu ke dalam list
email_attr_list = list(email_attr)

In [25]:
email_attr_list.sort()

In [26]:
print(email_attr_list)

['bcc', 'body', 'cc', 'from', 'subject', 'to']


## Files

In [53]:
myfile = open('text.txt', 'w')

In [54]:
myfile.write('halo text file!\n')

16

In [55]:
myfile.write('selamat tinggal text file!\n')

27

In [56]:
myfile.close()

In [57]:
myfile = open('text.txt')

In [58]:
myfile.readline()

'halo text file!\n'

In [59]:
myfile.readline()

'selamat tinggal text file!\n'

In [60]:
open('text.txt').read()

'halo text file!\nselamat tinggal text file!\n'

In [61]:
print(open('text.txt').read())

halo text file!
selamat tinggal text file!



In [62]:
x, y, z = 43, 44 , 45

In [63]:
message = 'Spam'

In [64]:
data = {'a':1, 'b':2}

In [65]:
list = [1,2,3]

In [66]:
file = open('text.txt', 'w')

In [67]:
file.write(message +'\n')

5

In [68]:
file.write('%s,%s,%s \n' % (x,y,z))

10

In [69]:
file.write(str(list) +'$' + str(data) +'\n')

27

In [70]:
file.close()

# Loops & Iterators

## while loops

In [72]:
message = "spam"
while message != '':
    print(message, end=' ')
    message = message[1:]

spam pam am m 

In [73]:
a = 0
b = 13

while a < b :
    print(a, end=' ')
    a = a + 1

0 1 2 3 4 5 6 7 8 9 10 11 12 

In [74]:
while True:
    name = input('Enter name: ')
    if name == 'stop': break
    age= input('Enter age: ')
    print('Hello' , name, '=>', int(age) **2)    

Enter name: kayla
Enter age: 21
Hello kayla => 441
Enter name: stop


## For Loops

In [75]:
for word in ['raka', 'billy', 'kode']:
    print(word, end ='\n')

raka
billy
kode


In [76]:
sum = 0
for i in [1,2,3,4]:
    sum = sum + i

sum

10

In [77]:
prod = 1
for item in [1,2,3,4]: prod *= item

prod

24

In [79]:
text = 'foxy fox'
words =  ('is', 'great', 'animal')

for chara in text: print(chara, end = ' ')

f o x y   f o x 

In [80]:
for word in words:print(word, end='...')

is...great...animal...

In [83]:
coor = [(1,2), (3,4), (5,6)]
for (x,y) in coor:
    print(x,y)

1 2
3 4
5 6


# Branching in Python

## if statement

In [1]:
if 1:
    print('true')

true


In [2]:
if not 1:
    print('true')
else:
    print('false')

false


In [6]:
age = input('enter your eage:')
if int(age) * 365 > 20000:
    print("time to retire!")
elif int(age) * 365 >10000:
    print('Lots of time left!')
else:
    print("time to get start!")

enter your eage:21
time to get start!


In [7]:
user_age = input('Enter your age: ')
age = int(user_age)* 365

if age >= 9490:
    print('You are a Jedi Master Now. Go learn from master Yoda!!')
elif age>=8395 and age < 9490:
    print('Becoming Jedi Knight')
else:
    print('You are a young Padawan')

Enter your age: 21
You are a young Padawan


# Functions & Packages

## Functions

In [8]:
def add(a, b):
    return a+b

add(5, 4)

9

In [9]:
add(6, 10)

16

In [12]:
add_things = add(10, 4)

In [13]:
add_things

14

In [14]:
add_things + 10

24

In [17]:
def add_and_print(a, b):
    print(a+b)

In [18]:
add_and_print(10, 20)

30


In [19]:
x = add_and_print(5, 3)

8


In [20]:
print(x)

None


In [21]:
def intersection(first_word, second_word):
    result = []
    for x in first_word:
        if x in second_word:
            result.append(x)
    return result

In [24]:
word1= 'spam'

In [25]:
word2 = 'scam'

In [26]:
char_of_intersect = intersection(word1, word2)

In [27]:
print(char_of_intersect)

['s', 'a', 'm']


## Modules & Built-in Function

In [1]:
print(abs(-123))

123


In [2]:
print(abs(123))

123


In [4]:
numbers = [1,2,3]
print(isinstance(numbers, list))

True


In [5]:
print(isinstance(numbers, dict))

False


In [6]:
number = 22
print(isinstance(number, list))

False


In [7]:
print(isinstance(number, int))

True


In [10]:
numbers = [1,2,3,4,5,6]
print(max(numbers))

6


In [11]:
print(min(numbers))

1


In [12]:
alphas = ['a', 'b', 'z']
print(max(alphas))

z


In [13]:
print(min(alphas))

a


In [14]:
languages = ['py', 'js', 'go', 'c']

In [15]:
print(languages.index('go'))

2


In [17]:
languages.sort()

In [18]:
print(languages)

['c', 'go', 'js', 'py']


In [19]:
name = 'raka'
print(name)

raka


In [20]:
name.replace('k', 'c')

'raca'

In [21]:
name.capitalize()

'Raka'

In [1]:
import math

In [2]:
print(math.factorial(3))

6


In [3]:
from math import factorial
from datetime import datetime
print(factorial(4))
print(datetime.now())

24
2022-09-10 12:04:27.142992


## Packages

In [1]:
import requests

In [2]:
r = requests.get('https://api.github.com/events')

In [3]:
print(r.status_code)

200


# Bonus Chapter
## Pengenalan Numpy

In [3]:
import numpy as np 

In [4]:
height = [1.75, 1.68, 1.8, 1.81, 1.69]
weight = [66.4, 49.22, 66.3, 88.56, 65.4]


In [5]:
np_height = np.array(height)

In [6]:
np_weight = np.array(weight)

In [7]:
bmi = np_weight/np_height ** 2

In [8]:
print(bmi)

[21.68163265 17.43905896 20.46296296 27.03214188 22.8983579 ]


In [9]:
numlist = [1,2,3]
nparray = np.array([1,2,3])
numlist +nparray

array([2, 4, 6])

In [10]:
bmi

array([21.68163265, 17.43905896, 20.46296296, 27.03214188, 22.8983579 ])

In [11]:
bmi > 24

array([False, False, False,  True, False])

In [12]:
bmi[bmi > 24]

array([27.03214188])

## NumPy Array 2D

In [14]:
import numpy as np
height = np.array([1.75, 1.68 , 1.8])
weight = np.array([66.4, 49.22, 66.3])

In [15]:
type(height)

numpy.ndarray

In [16]:
np_2d = np.array([[height], [weight]])

In [17]:
print(np_2d)

[[[ 1.75  1.68  1.8 ]]

 [[66.4  49.22 66.3 ]]]


In [18]:
np_2d.shape

(2, 1, 3)

In [23]:
np_2d = np.array([[1.75, 1.68 , 1.8],
       [66.4, 49.22, 66.3]]
      )

In [24]:
print(np_2d)

[[ 1.75  1.68  1.8 ]
 [66.4  49.22 66.3 ]]


In [25]:
np_2d.shape

(2, 3)

In [26]:
np_2d[0]

array([1.75, 1.68, 1.8 ])

In [27]:
np_2d[0][1]

1.68

In [29]:
np_2d[:, 1:3]

array([[ 1.68,  1.8 ],
       [49.22, 66.3 ]])

## Statistik Dasar dengan Numpy

In [30]:
height = np.round(np.random.normal(1.75, 0.2, 5000), 2)

In [31]:
height

array([1.81, 1.85, 1.82, ..., 1.83, 1.64, 1.48])

In [32]:
len(height)

5000

In [33]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)

In [34]:
weight

array([56.13, 66.24, 65.99, ..., 43.04, 46.96, 68.4 ])

In [35]:
len(weight)

5000

In [36]:
np_city = np.column_stack((height, weight))

In [37]:
np_city

array([[ 1.81, 56.13],
       [ 1.85, 66.24],
       [ 1.82, 65.99],
       ...,
       [ 1.83, 43.04],
       [ 1.64, 46.96],
       [ 1.48, 68.4 ]])

In [38]:
np.mean(np_city[:,0]) # rata rata tinggi badan

1.7508039999999998

In [39]:
np.median(np_city[:,0]) # median tinggi badan

1.75

In [40]:
np.mean(np_city[:,1]) # rata rata berat badan

60.83441400000001